[project]
name = "mydjporj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.0.3",
    "mssql-django>=1.5",
]
